<div class="grid grid-col-3 my-10 place-items-center">
	<img src="/learning-articles-images/cooling.webp" alt="cooling" class="mb-10 w-1/3" />
	<div class="text-4xl">Cooling</div>
</div>

<div class="mx-20">
	<p>
		To maintain computer components within acceptable working temperature ranges, computer cooling
		is necessary to remove the waste heat generated by those components. Integrated circuits such as
		central processing units (CPUs), chipsets, graphics cards, and hard disc drives are prone to
		temporary malfunction or permanent failure if they become overheated.
	</p>
	<div class="divider" />
	<p>
		Although computers and operating systems may be built to reduce power consumption and subsequent
		heating in response to workload and components that produce as little heat as feasible, more
		heat may still be produced than can be removed without consideration for cooling. The
		temperature rise caused by a particular amount of heat is decreased when airflow-cooled
		heatsinks are used. Hotspots can be avoided by paying attention to airflow patterns. Heatsink
		fans and computer fans are frequently used together to lower temperatures by actively expelling
		hot air. There are additionally more unusual cooling methods, such as liquid cooling. All
		current CPUs are built to shut down or reduce their voltage or clock speed if their internal
		temperature rises above a predetermined threshold. This is typically referred to as thermal
		throttling when clock speeds are reduced or thermal shutdown when the system or device is
		completely shut down.
	</p>
	<div class="divider" />
	<p>
		Cooling may be intended to cool a particular component or small region, or it may be intended to
		lower the ambient temperature inside the computer's case, such as by draining hot air (spot
		cooling). The CPU, graphics processing unit (GPU), and northbridge are examples of components
		that are frequently independently cooled.
	</p>
	<div class="divider" />
	<p>
		When natural convection is ineffective in removing heat, fans are deployed. Fans may be mounted
		to the computer case, or they may be affixed to power supply units (PSUs), hard drives,
		chipsets, GPUs, CPUs, or cards inserted into expansion slots. The following are typical fan
		sizes: 40, 60, 80, 92, 120, and 140 mm. High-end personal computers sometimes employ 200, 230,
		250, and 300 mm fans.
	</p>
</div>

<div class="grid my-10 place-items-center">
	<a href="/products/cooling" class="btn btn-primary">See cooling</a>
</div>
